import { Product, ProductType, FileFormat, Material, MaterialType, Color } from './types';

export const materials: Material[] = [
    { id: 'pla', name: MaterialType.PLA, priceMultiplier: 1.0 },
    { id: 'abs', name: MaterialType.ABS, priceMultiplier: 1.2 },
    { id: 'petg', name: MaterialType.PETG, priceMultiplier: 1.3 },
    { id: 'resin', name: MaterialType.RESIN, priceMultiplier: 1.8 },
];

export const colors: Color[] = [
    { id: 'white', name: 'Trắng', hex: '#FFFFFF' },
    { id: 'black', name: 'Đen', hex: '#000000' },
    { id: 'red', name: 'Đỏ', hex: '#EF4444' },
    { id: 'blue', name: 'Xanh dương', hex: '#3B82F6' },
    { id: 'green', name: 'Xanh lá', hex: '#10B981' },
    { id: 'yellow', name: 'Vàng', hex: '#F59E0B' },
    { id: 'purple', name: 'Tím', hex: '#A855F7' },
    { id: 'orange', name: 'Cam', hex: '#F97316' },
];

export const products: Product[] = [
    {
        id: '1',
        name: 'Mô hình rồng 3D',
        description: 'Mô hình rồng chi tiết cao với kích thước có thể tùy chỉnh. Hoàn hảo cho trang trí bàn làm việc hoặc làm quà tặng. File được tối ưu hóa cho in 3D FDM và Resin.',
        shortDescription: 'Mô hình rồng chi tiết cao, tuyệt đẹp',
        images: [
            'https://images.unsplash.com/photo-1633174524827-db00a6b7bc74?w=800&h=600&fit=crop',
            'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 150000,
        printBasePrice: 350000,
        fileFormats: [FileFormat.STL, FileFormat.OBJ],
        license: 'Personal Use',
        rating: 4.8,
        reviewCount: 124,
        featured: true,
        popular: true,
        category: 'Trang trí',
    },
    {
        id: '2',
        name: 'Bộ khay đựng đồ văn phòng',
        description: 'Bộ khay đựng bút, giấy note và phụ kiện văn phòng. Thiết kế tối giản, hiện đại. Dễ in, không cần支撑.',
        shortDescription: 'Khay đựng đồ văn phòng tiện dụng',
        images: [
            'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 80000,
        printBasePrice: 200000,
        fileFormats: [FileFormat.STL],
        license: 'Personal + Commercial',
        rating: 4.9,
        reviewCount: 89,
        featured: true,
        category: 'Tiện ích',
    },
    {
        id: '3',
        name: 'Móc khóa hình robot',
        description: 'Móc khóa robot dễ thương với nhiều tư thế khác nhau. In nhanh, ít vật liệu.',
        shortDescription: 'Móc khóa robot siêu cute',
        images: [
            'https://images.unsplash.com/photo-1563207153-f403bf289096?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 25000,
        printBasePrice: 50000,
        fileFormats: [FileFormat.STL],
        license: 'Personal Use',
        rating: 4.6,
        reviewCount: 256,
        popular: true,
        category: 'Phụ kiện',
    },
    {
        id: '4',
        name: 'Đèn ngủ hình mặt trăng',
        description: 'Đèn ngủ hình mặt trăng với bề mặt chi tiết miệng núi lửa. Cần kết hợp với module LED. File bao gồm cả đế đỡ.',
        shortDescription: 'Đèn ngủ mặt trăng siêu đẹp',
        images: [
            'https://images.unsplash.com/photo-1533406683-a3ecf0891e9f?w=800&h=600&fit=crop',
        ],
        type: ProductType.FILE,
        filePrice: 120000,
        fileFormats: [FileFormat.STL],
        license: 'Personal Use',
        rating: 4.9,
        reviewCount: 178,
        featured: true,
        category: 'Trang trí',
    },
    {
        id: '5',
        name: 'Giá đỡ điện thoại',
        description: 'Giá đỡ điện thoại gấp gọn, có thể điều chỉnh góc nghiêng. Tương thích với mọi kích thước điện thoại.',
        shortDescription: 'Giá đỡ điện thoại đa năng',
        images: [
            'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 45000,
        printBasePrice: 120000,
        fileFormats: [FileFormat.STL, FileFormat.OBJ],
        license: 'Personal + Commercial',
        rating: 4.7,
        reviewCount: 203,
        popular: true,
        category: 'Tiện ích',
    },
    {
        id: '6',
        name: 'Hộp đựng tai nghe',
        description: 'Hộp đựng tai nghe nhỏ gọn với khóa nam châm. Bảo vệ tai nghe khỏi bụi bẩn và trầy xước.',
        shortDescription: 'Hộp đựng tai nghe cao cấp',
        images: [
            'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=600&fit=crop',
        ],
        type: ProductType.PRINT,
        printBasePrice: 180000,
        rating: 4.5,
        reviewCount: 92,
        category: 'Phụ kiện',
    },
    {
        id: '7',
        name: 'Mô hình xe hơi cổ điển',
        description: 'Mô hình xe hơi cổ điển chi tiết cao. Có thể in từng bộ phận và lắp ráp. Phù hợp cho người yêu thích xe cổ.',
        shortDescription: 'Xe hơi cổ điển chi tiết',
        images: [
            'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
        ],
        type: ProductType.FILE,
        filePrice: 180000,
        fileFormats: [FileFormat.STL, FileFormat.OBJ],
        license: 'Personal Use',
        rating: 4.8,
        reviewCount: 67,
        category: 'Mô hình',
    },
    {
        id: '8',
        name: 'Chậu cây mini',
        description: 'Chậu cây mini với nhiều thiết kế độc đáo. Hoàn hảo cho cây xương rồng và cây mọng nước.',
        shortDescription: 'Chậu cây mini đa dạng',
        images: [
            'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 35000,
        printBasePrice: 85000,
        fileFormats: [FileFormat.STL],
        license: 'Personal + Commercial',
        rating: 4.9,
        reviewCount: 312,
        featured: true,
        popular: true,
        category: 'Trang trí',
    },
    {
        id: '9',
        name: 'Bookmark hình động vật',
        description: 'Bộ 5 bookmark hình các loài động vật dễ thương. In nhanh, dùng làm quà tặng hoặc bán lại.',
        shortDescription: 'Bookmark động vật siêu cute',
        images: [
            'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=600&fit=crop',
        ],
        type: ProductType.FILE,
        filePrice: 30000,
        fileFormats: [FileFormat.STL],
        license: 'Personal + Commercial',
        rating: 4.6,
        reviewCount: 145,
        category: 'Phụ kiện',
    },
    {
        id: '10',
        name: 'Bộ lắp ghép puzzle 3D',
        description: 'Puzzle 3D với các mảnh ghép tự do. Có thể tạo nhiều hình dạng khác nhau. Tuyệt vời cho trẻ em và người lớn.',
        shortDescription: 'Puzzle 3D sáng tạo',
        images: [
            'https://images.unsplash.com/photo-1587731556938-38755b4803a6?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 95000,
        printBasePrice: 280000,
        fileFormats: [FileFormat.STL, FileFormat.OBJ],
        license: 'Personal Use',
        rating: 4.7,
        reviewCount: 118,
        category: 'Đồ chơi',
    },
    {
        id: '11',
        name: 'Huy hiệu logo công ty',
        description: 'Template huy hiệu có thể tùy chỉnh logo. File được thiết kế để dễ dàng chỉnh sửa trong phần mềm 3D.',
        shortDescription: 'Huy hiệu logo tùy chỉnh',
        images: [
            'https://images.unsplash.com/photo-1565688534245-05d6b5be184a?w=800&h=600&fit=crop',
        ],
        type: ProductType.BOTH,
        filePrice: 50000,
        printBasePrice: 150000,
        fileFormats: [FileFormat.STL],
        license: 'Personal + Commercial',
        rating: 4.8,
        reviewCount: 87,
        category: 'Tiện ích',
    },
    {
        id: '12',
        name: 'Vỏ bảo vệ Nintendo Switch',
        description: 'Vỏ bảo vệ cho máy Nintendo Switch với thiết kế chống sốc và chống trượt. Dễ lắp đặt và tháo gỡ.',
        shortDescription: 'Vỏ bảo vệ Switch cao cấp',
        images: [
            'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&h=600&fit=crop',
        ],
        type: ProductType.FILE,
        filePrice: 75000,
        fileFormats: [FileFormat.STL],
        license: 'Personal Use',
        rating: 4.5,
        reviewCount: 234,
        popular: true,
        category: 'Phụ kiện',
    },
];

// Helper functions
export const getFeaturedProducts = () => products.filter(p => p.featured);
export const getPopularProducts = () => products.filter(p => p.popular);
export const getProductById = (id: string) => products.find(p => p.id === id);
